name: RPGLeveling
author: ArcasCZ
main: cz.arcas.rpgleveling.RPGLeveling
version: 1.2.0
commands:
   level:
      description: Get player level info.
      usage: /<command>
      permission: rpgleveling.level
      permission-message: You don't have <permission>
permissions:
   rpgleveling.*:
     description: Gives access to all RPGLeveling commands
     children:
       rpgleveling.level: true
   rpgleveling.level:
     description: Allows you to use level command
     default: true